resources:
  - ../../base/

patches:
  - target:
      kind: Deployment
      name: nginx
    patch: |-
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: nginx
                image: nginx:1.21
